### ISSUE TITLE
PET uptake model

### ISSUE THREAD

**Issue by oesteban** [nipreps/eddymotion#66]
Create one model that uses eddymotion's leave-one-volume-out framework to generate a motion-less target by interpolating from the "train" set of volumes, to then register the left-out volume to it.

cc/ @mnoergaard

**Comment by arokem** [comment]
As discussed on prep call, this can be more general than PET: for starters, this could be a time-series interpolation model that is agnostic to the specifics of the time-series, only assuming that neighboring time-points are similar to each other. Could take a variety of forms: linear interpolation, GP, spline interpolation. I suggest starting with linear interpolation first, because it's fast and simple.

At a second (?) stage, we could go more PET-specific, by using the PET-surfer model as a basis for volume and/or slice predictions. 

Both real and simulated data would be good for benchmarking and testing.

**Comment by arokem** [comment]
When generalizing to time-series, a good place to start would be to think about `ModelFactory` and whether we need to either generalize that to other use-cases (it's very DWI-specific right now), or whether we need to split it up into a `DWIModelFactory` and a `TimeSeriesModelFactory`.

**Comment by mnoergaard** [comment]
Thanks, Ariel! Post-meeting thoughts: Have to think about this a little bit more, but in an ideal model for PET, we need to take into account the time between volumes (frames) as they will often follow a sequence of short frames in the beginning and then longer frames in the end (an example is [20,20,20,60,60,60,120,120,120,300,300,600,600,600,600,600,600,600,600] seconds). In this regard, the tracer used will be important (11C, 18F) as it will provide information about the decay/half-life, and thereby what type of decay/signal (and SNR) is expected when leaving out a volume and then trying to predict it based on the remaining frames. This will be particularly important for the late frames. You suggested Gaussian processes, Arial, and in the case, I assume we should be able to add weights to the model fitting to take into account time between frames and signal decay.
